-- MySQL Script generated by MySQL Workbench
-- 09/28/17 01:10:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ICT3103
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ICT3103` ;

-- -----------------------------------------------------
-- Schema ICT3103
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ICT3103` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ICT3103` ;

-- -----------------------------------------------------
-- Table `ICT3103`.`AccountStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICT3103`.`AccountStatus` ;

CREATE TABLE IF NOT EXISTS `ICT3103`.`AccountStatus` (
  `accountStatus` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`accountStatus`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICT3103`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICT3103`.`Account` ;

CREATE TABLE IF NOT EXISTS `ICT3103`.`Account` (
  `accountID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `email` VARCHAR(200) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `phone` VARCHAR(20) NULL COMMENT '',
  `accountStatus` VARCHAR(50) NOT NULL COMMENT '',
  `profileImage` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`accountID`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `fk_Account_AccountStatus1_idx` (`accountStatus` ASC)  COMMENT '',
  CONSTRAINT `fk_Account_AccountStatus1`
    FOREIGN KEY (`accountStatus`)
    REFERENCES `ICT3103`.`AccountStatus` (`accountStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICT3103`.`FilePermission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICT3103`.`FilePermission` ;

CREATE TABLE IF NOT EXISTS `ICT3103`.`FilePermission` (
  `filePermission` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`filePermission`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICT3103`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICT3103`.`File` ;

CREATE TABLE IF NOT EXISTS `ICT3103`.`File` (
  `fileID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `accountID` INT NOT NULL COMMENT '',
  `fileName` VARCHAR(200) NOT NULL COMMENT '',
  `fileURL` VARCHAR(255) NOT NULL COMMENT '',
  `fileType` VARCHAR(10) NOT NULL COMMENT '',
  `fileSize` INT NOT NULL COMMENT '',
  `fileStatus` VARCHAR(50) NULL COMMENT '',
  `filePermission` VARCHAR(50) NOT NULL COMMENT '',
  `uploadDate` DATETIME NOT NULL COMMENT '',
  `expiryDate` DATETIME NULL COMMENT '',
  `downloadTimes` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`fileID`)  COMMENT '',
  INDEX `fk_File_Account1_idx` (`accountID` ASC)  COMMENT '',
  INDEX `fk_File_FilePermission1_idx` (`filePermission` ASC)  COMMENT '',
  CONSTRAINT `fk_File_Account1`
    FOREIGN KEY (`accountID`)
    REFERENCES `ICT3103`.`Account` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_File_FilePermission1`
    FOREIGN KEY (`filePermission`)
    REFERENCES `ICT3103`.`FilePermission` (`filePermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICT3103`.`FileSharing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICT3103`.`FileSharing` ;

CREATE TABLE IF NOT EXISTS `ICT3103`.`FileSharing` (
  `fileSharingID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fileID` INT NOT NULL COMMENT '',
  `accountID` INT NOT NULL COMMENT '',
  `invitationAccepted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`fileSharingID`)  COMMENT '',
  INDEX `fk_FileSharing_Account_idx` (`accountID` ASC)  COMMENT '',
  INDEX `fk_FileSharing_File1_idx` (`fileID` ASC)  COMMENT '',
  CONSTRAINT `fk_FileSharing_Account`
    FOREIGN KEY (`accountID`)
    REFERENCES `ICT3103`.`Account` (`accountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FileSharing_File1`
    FOREIGN KEY (`fileID`)
    REFERENCES `ICT3103`.`File` (`fileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ICT3103`.`AccountStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `ICT3103`;
INSERT INTO `ICT3103`.`AccountStatus` (`accountStatus`) VALUES ('Verified');
INSERT INTO `ICT3103`.`AccountStatus` (`accountStatus`) VALUES ('Unverified');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ICT3103`.`Account`
-- -----------------------------------------------------
START TRANSACTION;
USE `ICT3103`;
INSERT INTO `ICT3103`.`Account` (`accountID`, `name`, `email`, `password`, `phone`, `accountStatus`, `profileImage`) VALUES (1, 'Xinyi', '15SIC044T@sit.singaporetech.edu.sg', 'password', '12345678', 'Verified', NULL);
INSERT INTO `ICT3103`.`Account` (`accountID`, `name`, `email`, `password`, `phone`, `accountStatus`, `profileImage`) VALUES (2, 'Student', 'spammms@outlook.com', 'password', '12345678', 'Verified', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ICT3103`.`FilePermission`
-- -----------------------------------------------------
START TRANSACTION;
USE `ICT3103`;
INSERT INTO `ICT3103`.`FilePermission` (`filePermission`) VALUES ('Private');
INSERT INTO `ICT3103`.`FilePermission` (`filePermission`) VALUES ('Public');
INSERT INTO `ICT3103`.`FilePermission` (`filePermission`) VALUES ('Unlist');

COMMIT;

